### ISSUE TITLE
Setup.py defines two top-level packages

### ISSUE THREAD

**Issue by taschini** [blaflamme/more.mako#1]
The `setup.py` file defines two top-level packages: `more`, the namespace package hosting the actual package being developed, and `tests`, which contains its tests.

This is probably not a good idea, as installing `more.mako` will install also `tests` as a top-level package in `site-packages`:

```
$ python -V
Python 2.7.11
$ virtualenv env
$ ./env/bin/pip install -q git+ssh://git@github.com/morepath/more.mako.git
$ ls -1F ./env/lib/python2.7/site-packages/tests/
__init__.py
__init__.pyc
fixtures/
test_mako.py
test_mako.pyc
```

There are three ways to solve this:
1. Move the `tests` package into the `more/mako` directory;
2. Remove the `__init__.py` file from `tests`;
3. Manually define the packages in `setup.py` instead of  `packages=find_packages()`.

In all other Morepath extensions, option (1) is what is being used, and, in the spirit of least surprise, I would use that in here too.

**Comment by blaflamme** [comment]
@taschini thanks for raising out this issue, I agree the same convention should be used.
