### ISSUE TITLE
Update supported Python versions

### ISSUE THREAD

**Issue by jugmac00** [blaflamme/more.mako#4]
- drop support for Python versions < 3.6
- add support for Python versions 3.7, 3.8 (if missing)
- fix linting errors (if present)

If you are a beginner, and need to help for this issue, especially during Hacktoberfest, please comment here or reach out to me via https://jugmac00.github.io/

**Comment by rahulob** [comment]
I like to work on that

**Comment by jugmac00** [comment]
Great to hear that!

Before you start, please have a look at the current test failures:
https://travis-ci.org/github/morepath/more.mako/jobs/731640660

These indicate, there is not only the Python update to be done, but also there is a problem with test collection.

This is a problem I would have to do some research myself.

If this is too hard for you, you can have a look at the many other open issues in this organization:
https://github.com/search?q=org%3Amorepath+Update+supported+Python+versions&type=issues

**Comment by jugmac00** [comment]
You can use `usedevelop=True` in the testenv section of tox.ini to counter the above mentioned problem.

**Comment by jugmac00** [comment]
@rahuljandial2 Any update?

**Comment by rahulob** [comment]
I find it difficult. I am a beginner. Sorry for that.

**Comment by jugmac00** [comment]
I am here to help!

**Comment by jugmac00** [comment]
There was a similar issue in another project where I explained, see here https://github.com/morepath/morepath_cerebral_todomvc/issues/2

I also created a video to explain some basics.. https://www.youtube.com/watch?v=JoOsVGqsehM&t=3s

Do not hesitate to ask questions.

Maybe as a starter... do you know Python already? Do you know anything about packaging, testing and linting?

**Comment by rahulob** [comment]
I have basic knowledge about python what should i need to know to solve this issue.

**Comment by jugmac00** [comment]
This is a library, which not only supports one Python version, but several.

It should support Python 3.6 - 3.8.

This means, we have to run the tests against these versions and make sure they all work.

You could create a virtualenv for 3.6, 3.7 and one for 3.8 - but this is cumbersome.

So, we use a tool which does that for us - this tool is called tox.

Tox then creates all these environments and runs the tests.

So, your first tasks are
- clone this repository to your computer
- change into this directory
- install `tox` https://tox.readthedocs.io/en/latest/ and run it
- you should see some errors - we will walk you through to fix them

Installation depends on your operating system. Do not install tox in your system interpreter, but either in a virtual environment itself, or via pipx or do a `pip(3) install tox --user`.

Once again, do not hesitate to ask questions.

( a lot of this was already explained in the above mentioned issue ).

**Comment by rahulob** [comment]
Thanks a lot.

I will definitely look into this.
